### ISSUE TITLE
When pann extracts audio features with much smaller dimensions than video features, the code runs incorrectly.

### ISSUE THREAD

**Issue by ffiioonnaa** [line/lighthouse#34] opened 2024-09-13 03:48 UTC
Hi，thanks for your work! I'm running into some problems and I'd like to ask you some questions.
1. I have a video which duration is 116s，saliency scores(ground truth) size(58,3)，relevant_clip_ids size(58)， audio features size(33,2048)，video features size(59, 2816) ，ctx_l=33, and then I got an error : 
cg_detr_dataset.py", line 301, in get_saliency_labels_all
score_array_new[:ctx_l] = score_array
could not broadcast input array from shape (34,) into shape (33,)

       def get_saliency_labels_all(self, rel_clip_ids, scores, ctx_l, max_n=1, add_easy_negative=True):
        ...

        # score_array = [min(agg_scores[idx], ctx_l-1) for idx in range(ctx_l)]
        score_array = np.zeros(ctx_l)
        for idx in range(len(rel_clip_ids)):
            if rel_clip_ids[idx] >= ctx_l:
                score_array_new = np.zeros(ctx_l + 1)
                score_array_new[:ctx_l] = score_array
                score_array = score_array_new
            score_array[rel_clip_ids[idx]] = agg_scores[idx]
I find that, when the element in relevant_clip_ids is greater than ctx_l, it will report an error here： score_array_new[:ctx_l] = score_array. How can I change this? And I'm wondering that why  audio features dimensions could be smaller so much than video feathures，will such data bring negative impact in training process?

2. I was hoping to make some tweaks based on that work that would make it possible for the model to input just the video, not the prompt, and for the model to give a score for each 2 second clip.My dataset was labeled with a score for every 2 seconds clip without mr windows，can I just set model_inputs["span_labels"] = torch.tensor([[0., 0.]]) and q_feat = np.zeros([32,512]) in dataloader?

**Comment by awkrail** [comment] 2024-09-13 04:12
@ffiioonnaa Thank you for your feedback!

> I have a video which duration is 116s，saliency scores(ground truth) size(58,3)，relevant_clip_ids size(58)， audio features size(33,2048)，video features size(59, 2816) ，ctx_l=33, and then I got an error :
cg_detr_dataset.py", line 301, in get_saliency_labels_all
score_array_new[:ctx_l] = score_array
could not broadcast input array from shape (34,) into shape (33,). I find that, when the element in relevant_clip_ids is greater than ctx_l, it will report an error here： score_array_new[:ctx_l] = score_array. How can I change this?

Is this your own dataset, not QVHighlights? The current training code supports only the benchmarks, so I didn't meet this issue. Let me take some time to reproduce this issue for one week.

> And I'm wondering that why audio features dimensions could be smaller so much than video feathures，will such data bring negative impact in training process?

Yes, I think that the length of audio features should be equal to video features. For example, in QVHighlights, the video length is 75 (0.5 fps, 150s videos, 75 x video_dim) and the audio feature has also 75 length (75 x audio_dim).

> I was hoping to make some tweaks based on that work that would make it possible for the model to input just the video, not the prompt, and for the model to give a score for each 2 second clip.My dataset was labeled with a score for every 2 seconds clip without mr windows，can I just set model_inputs["span_labels"] = torch.tensor([[0., 0.]]) and q_feat = np.zeros([32,512]) in dataloader?

Let me take 1 week to investigate it. If you can, could you share one example video-query pair with me? My mail address is taichitary@gmail.com

**Comment by awkrail** [comment] 2024-09-23 05:57
I conclude that this error occurs due to the difference of video and audio feature length. I close this issue. In the future version, I will prepare for the custom dataset training.

**Closed by awkrail** 2024-09-23 05:57 UTC
